# -*- coding: utf-8 -*-
"""Sudoku generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zVr_XoU1YqvutfeLFT_AVP_6e7iBWdjF
"""

!pip install dokusan

from dokusan import generators
import numpy as np

arr = np.array(list(str(generators.random_sudoku(avg_rank=150))))
print(arr.reshape(9,9))